# Generated by Django 5.2.7 on 2025-11-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='region',
            field=models.CharField(default='Kanto', max_length=50),
        ),
    ]
